-- PractiCore PostgreSQL schema for Supabase.
--
-- Converted from the authoritative MariaDB dump of the `practicore` database
-- (migrations/mysql_schema_dump.sql - mysqldump --no-data with every migration
-- 001-014 already applied) by migrations/mysql_to_postgres.py. This file is the
-- single source of truth for a fresh Postgres database; the numbered MySQL
-- files in this folder remain as history for the MySQL repository
-- (PractiCore---mysql).
--
-- Apply: paste into the Supabase SQL Editor, or
--   psql "$DATABASE_URL" -f migrations/000_full_schema.sql
--
-- Re-running drops and recreates every table, so only use on a fresh database.

DROP TABLE IF EXISTS applications CASCADE;
CREATE TABLE applications (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_id integer NOT NULL,
    posting_id integer NOT NULL,
    status text NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending', 'In Review', 'Reviewed', 'Shortlisted', 'Scheduled', 'Hired', 'Rejected')),
    match_score integer NOT NULL DEFAULT 0,
    resume_match_score smallint DEFAULT NULL,
    assessment_match_score smallint DEFAULT NULL,
    employer_notes text DEFAULT NULL,
    applied_on timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_applications_student_posting UNIQUE (student_id, posting_id)
);

DROP TABLE IF EXISTS assessment_attempts CASCADE;
CREATE TABLE assessment_attempts (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_id integer NOT NULL,
    posting_id integer DEFAULT NULL,
    attempt_no integer NOT NULL DEFAULT 1,
    overall_percentage integer NOT NULL DEFAULT 0,
    total_correct integer NOT NULL DEFAULT 0,
    total_questions integer NOT NULL DEFAULT 0,
    competency_level varchar(60) DEFAULT NULL,
    taken_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    submitted_at timestamp NULL DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_attempt UNIQUE (student_id, attempt_no, posting_id)
);

DROP TABLE IF EXISTS assessment_domain_scores CASCADE;
CREATE TABLE assessment_domain_scores (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_id integer NOT NULL,
    domain varchar(100) NOT NULL,
    correct integer NOT NULL DEFAULT 0,
    total integer NOT NULL DEFAULT 0,
    score_percent integer NOT NULL DEFAULT 0,
    track_code varchar(20) DEFAULT NULL,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_assessment_domain_student UNIQUE (student_id, domain)
);

DROP TABLE IF EXISTS assessment_questions CASCADE;
CREATE TABLE assessment_questions (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    question_code varchar(30) DEFAULT NULL,
    course_track varchar(50) NOT NULL,
    category varchar(100) NOT NULL,
    competency varchar(100) DEFAULT NULL,
    doc_competency varchar(60) DEFAULT NULL,
    set_id integer DEFAULT NULL,
    target_role varchar(100) NOT NULL,
    pathway varchar(100) DEFAULT NULL,
    source_type text DEFAULT NULL CHECK (source_type IN ('Researcher-Developed', 'Framework-Derived', 'Research-Supported', 'Validation-Approved')),
    key_status varchar(20) NOT NULL DEFAULT 'Verified',
    question_type varchar(40) NOT NULL DEFAULT 'Multiple Choice',
    difficulty text NOT NULL DEFAULT 'medium' CHECK (difficulty IN ('easy', 'medium', 'hard')),
    standard_ref varchar(100) NOT NULL,
    question_text text NOT NULL,
    option_a text NOT NULL,
    option_b text NOT NULL,
    option_c text NOT NULL,
    option_d text NOT NULL,
    correct_option varchar(1) NOT NULL,
    explanation text DEFAULT NULL,
    model_answer varchar(255) DEFAULT NULL,
    option_json text DEFAULT NULL,
    position integer DEFAULT NULL,
    is_active smallint NOT NULL DEFAULT 1,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_assessment_questions_code UNIQUE (question_code)
);

DROP TABLE IF EXISTS attempt_competencies CASCADE;
CREATE TABLE attempt_competencies (
    attempt_id integer NOT NULL,
    competency_code varchar(30) NOT NULL,
    set_id integer DEFAULT NULL,
    correct_count integer NOT NULL DEFAULT 0,
    question_count integer NOT NULL DEFAULT 0,
    score_percent integer NOT NULL DEFAULT 0,
    PRIMARY KEY (attempt_id, competency_code)
);

DROP TABLE IF EXISTS attempt_questions CASCADE;
CREATE TABLE attempt_questions (
    attempt_id integer NOT NULL,
    question_id integer NOT NULL,
    display_order integer NOT NULL DEFAULT 0,
    selected_answer varchar(255) DEFAULT NULL,
    is_correct smallint NOT NULL DEFAULT 0,
    answered_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (attempt_id, question_id)
);

DROP TABLE IF EXISTS compatibility_scores CASCADE;
CREATE TABLE compatibility_scores (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_id integer NOT NULL,
    posting_id integer NOT NULL,
    assessment_score integer NOT NULL DEFAULT 0,
    evidence_score integer NOT NULL DEFAULT 0,
    total_score integer NOT NULL DEFAULT 0,
    competencies_met integer NOT NULL DEFAULT 0,
    competencies_total integer NOT NULL DEFAULT 0,
    detail text DEFAULT NULL,
    computed_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_compat UNIQUE (student_id, posting_id)
);

DROP TABLE IF EXISTS competencies CASCADE;
CREATE TABLE competencies (
    code varchar(30) NOT NULL,
    name varchar(100) NOT NULL,
    track varchar(50) NOT NULL,
    is_core smallint NOT NULL DEFAULT 0,
    description varchar(255) DEFAULT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    PRIMARY KEY (code)
);

DROP TABLE IF EXISTS competency_skill_map CASCADE;
CREATE TABLE competency_skill_map (
    skill_key varchar(60) NOT NULL,
    competency_code varchar(30) NOT NULL,
    strength text NOT NULL DEFAULT 'supporting' CHECK (strength IN ('primary', 'supporting')),
    PRIMARY KEY (skill_key, competency_code)
);

DROP TABLE IF EXISTS employers CASCADE;
CREATE TABLE employers (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id integer DEFAULT NULL,
    company_name varchar(150) NOT NULL,
    company_logo_text varchar(255) DEFAULT NULL,
    logo_path varchar(255) DEFAULT NULL,
    industry varchar(120) DEFAULT NULL,
    location varchar(100) NOT NULL,
    about text DEFAULT NULL,
    required_skills text DEFAULT NULL,
    contact_name varchar(100) DEFAULT NULL,
    contact_phone varchar(30) DEFAULT NULL,
    contact_position varchar(100) DEFAULT NULL,
    website varchar(150) DEFAULT NULL,
    company_size varchar(50) DEFAULT NULL,
    is_hiring smallint NOT NULL DEFAULT 1,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_employers_user_id UNIQUE (user_id)
);

DROP TABLE IF EXISTS internship_competency_requirements CASCADE;
CREATE TABLE internship_competency_requirements (
    posting_id integer NOT NULL,
    competency_code varchar(30) NOT NULL,
    importance text NOT NULL DEFAULT 'preferred' CHECK (importance IN ('essential', 'preferred')),
    required_percent integer NOT NULL DEFAULT 60,
    PRIMARY KEY (posting_id, competency_code)
);

DROP TABLE IF EXISTS internship_postings CASCADE;
CREATE TABLE internship_postings (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    employer_id integer NOT NULL,
    title varchar(150) NOT NULL,
    department varchar(100) DEFAULT NULL,
    description text NOT NULL,
    is_remote smallint DEFAULT 0,
    status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'closed')),
    positions_available integer NOT NULL DEFAULT 1,
    posted_date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS posting_skills CASCADE;
CREATE TABLE posting_skills (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    posting_id integer NOT NULL,
    skill_name varchar(100) NOT NULL,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS question_exposure_history CASCADE;
CREATE TABLE question_exposure_history (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_id integer NOT NULL,
    competency_code varchar(30) NOT NULL,
    set_id integer NOT NULL,
    attempt_id integer DEFAULT NULL,
    exposed_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS question_key_corrections CASCADE;
CREATE TABLE question_key_corrections (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    question_code varchar(30) NOT NULL,
    recorded_option varchar(1) NOT NULL,
    applied_option varchar(1) NOT NULL,
    recorded_option_text varchar(255) DEFAULT NULL,
    applied_option_text varchar(255) DEFAULT NULL,
    explanation text DEFAULT NULL,
    rule varchar(80) NOT NULL DEFAULT 'explanation-token-match',
    source_document varchar(120) NOT NULL DEFAULT 'PractiCore_Final_Research_Based_Question_Bank.docx',
    corrected_by varchar(80) NOT NULL DEFAULT 'flask seed-master-bank',
    corrected_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_key_correction UNIQUE (question_code)
);

DROP TABLE IF EXISTS question_seen_history CASCADE;
CREATE TABLE question_seen_history (
    student_id integer NOT NULL,
    question_id integer NOT NULL,
    competency_code varchar(30) NOT NULL,
    attempt_id integer DEFAULT NULL,
    times_seen integer NOT NULL DEFAULT 1,
    last_seen_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (student_id, question_id)
);

DROP TABLE IF EXISTS question_set_members CASCADE;
CREATE TABLE question_set_members (
    set_id integer NOT NULL,
    question_id integer NOT NULL,
    PRIMARY KEY (set_id, question_id)
);

DROP TABLE IF EXISTS question_sets CASCADE;
CREATE TABLE question_sets (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    competency_code varchar(30) NOT NULL,
    set_code varchar(1) NOT NULL,
    label varchar(60) NOT NULL,
    question_count integer NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT uq_competency_set UNIQUE (competency_code, set_code)
);

DROP TABLE IF EXISTS resume_competency_evidence CASCADE;
CREATE TABLE resume_competency_evidence (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_id integer NOT NULL,
    competency_code varchar(30) NOT NULL,
    evidence_skills text NOT NULL,
    evidence_count integer NOT NULL DEFAULT 0,
    has_project smallint NOT NULL DEFAULT 0,
    has_experience smallint NOT NULL DEFAULT 0,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_resume_evidence UNIQUE (student_id, competency_code)
);

DROP TABLE IF EXISTS student_competency_scores CASCADE;
CREATE TABLE student_competency_scores (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_id integer NOT NULL,
    competency_code varchar(30) NOT NULL,
    score_percent integer NOT NULL DEFAULT 0,
    attempts_count integer NOT NULL DEFAULT 0,
    best_percent integer NOT NULL DEFAULT 0,
    last_attempt_id integer DEFAULT NULL,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_student_competency UNIQUE (student_id, competency_code)
);

DROP TABLE IF EXISTS student_resumes CASCADE;
CREATE TABLE student_resumes (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_id integer NOT NULL,
    filename varchar(255) NOT NULL,
    mime_type varchar(100) NOT NULL,
    file_size integer NOT NULL,
    education text DEFAULT NULL,
    certifications text DEFAULT NULL,
    experience text DEFAULT NULL,
    projects text DEFAULT NULL,
    file_data bytea NOT NULL,
    uploaded_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_student_resumes_student UNIQUE (student_id)
);

DROP TABLE IF EXISTS students CASCADE;
CREATE TABLE students (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id integer DEFAULT NULL,
    student_no varchar(20) NOT NULL,
    username varchar(50) NOT NULL,
    password_hash varchar(255) DEFAULT NULL,
    email varchar(120) NOT NULL,
    name varchar(100) NOT NULL,
    course varchar(120) NOT NULL,
    skills text DEFAULT NULL,
    phone varchar(20) DEFAULT NULL,
    year_level varchar(20) DEFAULT '4th Year',
    avatar_path varchar(255) DEFAULT NULL,
    resume_path varchar(255) DEFAULT NULL,
    assessment_score integer DEFAULT 0,
    total_questions integer DEFAULT 0,
    competency_level varchar(50) DEFAULT 'Not Assessed',
    resume_match_rate integer DEFAULT 0,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT student_no UNIQUE (student_no),
    CONSTRAINT username UNIQUE (username),
    CONSTRAINT email UNIQUE (email),
    CONSTRAINT uq_students_user_id UNIQUE (user_id)
);

DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email varchar(120) NOT NULL,
    username varchar(50) DEFAULT NULL,
    password_hash varchar(255) NOT NULL,
    role text NOT NULL CHECK (role IN ('student', 'employer', 'admin')),
    is_active smallint NOT NULL DEFAULT 1,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT users_email UNIQUE (email),
    CONSTRAINT users_username UNIQUE (username)
);

CREATE INDEX fk_applications_posting ON applications (posting_id);
CREATE INDEX idx_assessment_attempts_student ON assessment_attempts (student_id, taken_at);
CREATE INDEX idx_attempt_student ON assessment_attempts (student_id);
CREATE INDEX idx_assessment_questions_pool ON assessment_questions (is_active, competency, difficulty);
CREATE INDEX idx_assessment_questions_active ON assessment_questions (is_active, question_code);
CREATE INDEX fk_ac_competency ON attempt_competencies (competency_code);
CREATE INDEX idx_aq_question ON attempt_questions (question_id, attempt_id);
CREATE INDEX fk_cs_posting ON compatibility_scores (posting_id);
CREATE INDEX idx_csm_competency ON competency_skill_map (competency_code);
CREATE INDEX idx_icr_competency ON internship_competency_requirements (competency_code);
CREATE INDEX employer_id ON internship_postings (employer_id);
CREATE INDEX idx_posting_status ON internship_postings (status, posted_date);
CREATE INDEX posting_id ON posting_skills (posting_id);
CREATE INDEX idx_exposure_student ON question_exposure_history (student_id, competency_code);
CREATE INDEX fk_exposure_set ON question_exposure_history (set_id);
CREATE INDEX idx_qsh_student ON question_seen_history (student_id, competency_code);
CREATE INDEX idx_qsh_stale ON question_seen_history (student_id, competency_code, last_seen_at);
CREATE INDEX fk_qsh_question ON question_seen_history (question_id);
CREATE INDEX fk_qsh_competency ON question_seen_history (competency_code);
CREATE INDEX idx_qsm_question ON question_set_members (question_id);
CREATE INDEX fk_rce_competency ON resume_competency_evidence (competency_code);
CREATE INDEX fk_scs_competency ON student_competency_scores (competency_code);

ALTER TABLE applications ADD CONSTRAINT fk_applications_posting FOREIGN KEY (posting_id) REFERENCES internship_postings (id) ON DELETE CASCADE;
ALTER TABLE applications ADD CONSTRAINT fk_applications_student FOREIGN KEY (student_id) REFERENCES students (id) ON DELETE CASCADE;
ALTER TABLE assessment_attempts ADD CONSTRAINT fk_assessment_attempts_student FOREIGN KEY (student_id) REFERENCES students (id) ON DELETE CASCADE;
ALTER TABLE assessment_domain_scores ADD CONSTRAINT fk_assessment_domain_student FOREIGN KEY (student_id) REFERENCES students (id) ON DELETE CASCADE;
ALTER TABLE attempt_competencies ADD CONSTRAINT fk_ac_attempt FOREIGN KEY (attempt_id) REFERENCES assessment_attempts (id) ON DELETE CASCADE;
ALTER TABLE attempt_competencies ADD CONSTRAINT fk_ac_competency FOREIGN KEY (competency_code) REFERENCES competencies (code) ON DELETE CASCADE;
ALTER TABLE attempt_questions ADD CONSTRAINT fk_aq_attempt FOREIGN KEY (attempt_id) REFERENCES assessment_attempts (id) ON DELETE CASCADE;
ALTER TABLE attempt_questions ADD CONSTRAINT fk_aq_question FOREIGN KEY (question_id) REFERENCES assessment_questions (id) ON DELETE CASCADE;
ALTER TABLE compatibility_scores ADD CONSTRAINT fk_cs_posting FOREIGN KEY (posting_id) REFERENCES internship_postings (id) ON DELETE CASCADE;
ALTER TABLE compatibility_scores ADD CONSTRAINT fk_cs_student FOREIGN KEY (student_id) REFERENCES students (id) ON DELETE CASCADE;
ALTER TABLE competency_skill_map ADD CONSTRAINT fk_csm_competency FOREIGN KEY (competency_code) REFERENCES competencies (code) ON DELETE CASCADE;
ALTER TABLE employers ADD CONSTRAINT fk_employers_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE internship_competency_requirements ADD CONSTRAINT fk_icr_competency FOREIGN KEY (competency_code) REFERENCES competencies (code) ON DELETE CASCADE;
ALTER TABLE internship_competency_requirements ADD CONSTRAINT fk_icr_posting FOREIGN KEY (posting_id) REFERENCES internship_postings (id) ON DELETE CASCADE;
ALTER TABLE internship_postings ADD CONSTRAINT internship_postings_ibfk_1 FOREIGN KEY (employer_id) REFERENCES employers (id) ON DELETE CASCADE;
ALTER TABLE posting_skills ADD CONSTRAINT posting_skills_ibfk_1 FOREIGN KEY (posting_id) REFERENCES internship_postings (id) ON DELETE CASCADE;
ALTER TABLE question_exposure_history ADD CONSTRAINT fk_exposure_set FOREIGN KEY (set_id) REFERENCES question_sets (id) ON DELETE CASCADE;
ALTER TABLE question_exposure_history ADD CONSTRAINT fk_exposure_student FOREIGN KEY (student_id) REFERENCES students (id) ON DELETE CASCADE;
ALTER TABLE question_key_corrections ADD CONSTRAINT fk_key_correction_question FOREIGN KEY (question_code) REFERENCES assessment_questions (question_code) ON DELETE CASCADE;
ALTER TABLE question_seen_history ADD CONSTRAINT fk_qsh_competency FOREIGN KEY (competency_code) REFERENCES competencies (code) ON DELETE CASCADE;
ALTER TABLE question_seen_history ADD CONSTRAINT fk_qsh_question FOREIGN KEY (question_id) REFERENCES assessment_questions (id) ON DELETE CASCADE;
ALTER TABLE question_seen_history ADD CONSTRAINT fk_qsh_student FOREIGN KEY (student_id) REFERENCES students (id) ON DELETE CASCADE;
ALTER TABLE question_set_members ADD CONSTRAINT fk_qsm_question FOREIGN KEY (question_id) REFERENCES assessment_questions (id) ON DELETE CASCADE;
ALTER TABLE question_set_members ADD CONSTRAINT fk_qsm_set FOREIGN KEY (set_id) REFERENCES question_sets (id) ON DELETE CASCADE;
ALTER TABLE question_sets ADD CONSTRAINT fqs_competency FOREIGN KEY (competency_code) REFERENCES competencies (code) ON DELETE CASCADE;
ALTER TABLE resume_competency_evidence ADD CONSTRAINT fk_rce_competency FOREIGN KEY (competency_code) REFERENCES competencies (code) ON DELETE CASCADE;
ALTER TABLE resume_competency_evidence ADD CONSTRAINT fk_rce_student FOREIGN KEY (student_id) REFERENCES students (id) ON DELETE CASCADE;
ALTER TABLE student_competency_scores ADD CONSTRAINT fk_scs_competency FOREIGN KEY (competency_code) REFERENCES competencies (code) ON DELETE CASCADE;
ALTER TABLE student_competency_scores ADD CONSTRAINT fk_scs_student FOREIGN KEY (student_id) REFERENCES students (id) ON DELETE CASCADE;
ALTER TABLE student_resumes ADD CONSTRAINT fk_student_resumes_student FOREIGN KEY (student_id) REFERENCES students (id) ON DELETE CASCADE;
ALTER TABLE students ADD CONSTRAINT fk_students_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at := CURRENT_TIMESTAMP; RETURN NEW; END $$;
CREATE TRIGGER trg_assessment_domain_scores_updated_at BEFORE UPDATE ON assessment_domain_scores FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_resume_competency_evidence_updated_at BEFORE UPDATE ON resume_competency_evidence FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_student_competency_scores_updated_at BEFORE UPDATE ON student_competency_scores FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_students_updated_at BEFORE UPDATE ON students FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE OR REPLACE FUNCTION set_computed_at() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN NEW.computed_at := CURRENT_TIMESTAMP; RETURN NEW; END $$;
CREATE TRIGGER trg_compatibility_scores_computed_at BEFORE UPDATE ON compatibility_scores FOR EACH ROW EXECUTE FUNCTION set_computed_at();

CREATE OR REPLACE FUNCTION set_uploaded_at() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN NEW.uploaded_at := CURRENT_TIMESTAMP; RETURN NEW; END $$;
CREATE TRIGGER trg_student_resumes_uploaded_at BEFORE UPDATE ON student_resumes FOR EACH ROW EXECUTE FUNCTION set_uploaded_at();

