"""Convert the authoritative MariaDB dump (practicore, all migrations 001-014
applied) into a PostgreSQL schema for Supabase.

Run (from the repo root):  python migrations/mysql_to_postgres.py
Out:  migrations/000_full_schema.sql

Conversions:
  * int AUTO_INCREMENT      -> integer GENERATED BY DEFAULT AS IDENTITY
  * tinyint[(1)] [unsigned] -> smallint   (keeps 1/0 semantics the code expects)
  * enum(...)               -> text + column CHECK (... IN (...))
  * mediumblob/longblob     -> bytea
  * char(n)                 -> varchar(n)  (no blank-padding semantics)
  * ON UPDATE CURRENT_TIMESTAMP -> dropped here, rebuilt as triggers at the end
  * ENGINE/CHARSET/COLLATE/COMMENT/display widths -> dropped
  * UNIQUE KEY -> table-level UNIQUE constraint; KEY -> CREATE INDEX (deduped)
  * FKs are stripped from CREATE TABLE and re-added as ALTER TABLE after every
    table exists, so load order can never break on a missing reference.

The script FAILS LOUDLY on a type or construct it does not recognise rather
than emitting SQL that might be subtly wrong.
"""
import re
from collections import OrderedDict

SRC = "migrations/mysql_schema_dump.sql"
OUT = "migrations/000_full_schema.sql"

IDENTITY = " GENERATED BY DEFAULT AS IDENTITY"

tables = OrderedDict()   # name -> dict of parsed parts


def map_type(type_name, size, col, table):
    """Maps one MariaDB type to its PostgreSQL type. Raises on anything odd."""
    t = type_name.lower()
    if t == "int":
        return "integer"
    if t in ("tinyint", "smallint", "mediumint"):
        return "smallint"          # tinyint(1) keeps 1/0 as int, per the code
    if t == "bigint":
        return "bigint"
    if t == "varchar":
        return "varchar(%s)" % size
    if t == "char":
        return "varchar(%s)" % size  # avoid bpchar blank padding
    if t in ("text", "longtext", "mediumtext"):
        return "text"
    if t in ("blob", "tinyblob", "mediumblob", "longblob"):
        return "bytea"
    if t in ("timestamp", "datetime"):
        return "timestamp"
    if t == "double":
        return "double precision"
    if t == "float":
        return "real"
    if t in ("decimal", "numeric"):
        return "numeric(%s)" % size
    if t == "json":
        return "json"
    if t == "year":
        return "smallint"
    raise SystemExit("UNKNOWN TYPE %r on %s.%s - update the converter" % (type_name, table, col))


def parse_enum_values(inner):
    return re.findall(r"'((?:[^']|'')*)'", inner)


def convert_column(table, line):
    """Returns (column_name, converted_line, on_update_flag)."""
    line = line.rstrip()
    if line.endswith(","):
        line = line[:-1]
    m = re.match(r"^\s+`(\w+)`\s+(.+)$", line)
    if not m:
        raise SystemExit("BAD COLUMN LINE in %s: %r" % (table, line))
    col, rest = m.group(1), m.group(2).strip()

    # ON UPDATE -> trigger later (Postgres has no inline form)
    on_update = False
    if re.search(r"\bON\s+UPDATE\s+current_timestamp\(\)", rest, re.IGNORECASE):
        on_update = True
        rest = re.sub(r"\bON\s+UPDATE\s+current_timestamp\(\)", "", rest,
                      flags=re.IGNORECASE).strip()

    # Column COMMENT and column-level charset/collation -> dropped
    rest = re.sub(r"\bCOMMENT\s+'[^']*'", "", rest).strip()
    rest = re.sub(r"\bCHARACTER\s+SET\s+\w+", "", rest, flags=re.IGNORECASE).strip()
    rest = re.sub(r"\bCOLLATE\s+\w+", "", rest, flags=re.IGNORECASE).strip()
    # MariaDB auto increment flag
    identity = bool(re.search(r"\bAUTO_INCREMENT\b", rest))
    rest = re.sub(r"\bAUTO_INCREMENT\b", "", rest).strip()
    # unsigned -> Postgres has none; values fit
    rest = re.sub(r"\bunsigned\b", "", rest, flags=re.IGNORECASE).strip()

    enum_values = None
    em = re.match(r"^enum\(([^)]*)\)\s*(.*)$", rest, re.IGNORECASE)
    if em:
        enum_values = parse_enum_values(em.group(1))
        rest = em.group(2).strip()
        pg_type = "text"
    else:
        tm = re.match(r"^([A-Za-z]+)(\(([\d,]+)\))?\s*(.*)$", rest)
        if not tm:
            raise SystemExit("CANNOT PARSE %s.%s: %r" % (table, col, rest))
        pg_type = map_type(tm.group(1), tm.group(3), col, table)
        rest = tm.group(4).strip()

    # MariaDB allows current_timestamp() everywhere; Postgres does not
    rest = re.sub(r"current_timestamp\(\)", "CURRENT_TIMESTAMP", rest,
                  flags=re.IGNORECASE)
    # bit defaults like b'0'
    rest = re.sub(r"\bb'0'\b", "0", rest)
    rest = re.sub(r"\bb'1'\b", "1", rest)

    if enum_values:
        check = " CHECK (%s IN (%s))" % (
            col, ", ".join("'" + v.replace("'", "''") + "'" for v in enum_values))
        rest = (rest + check).strip()

    out = "%s %s%s" % (col, pg_type, IDENTITY if identity else "")
    if rest:
        out += " " + rest
    return col, out, on_update


def convert():
    lines = open(SRC, encoding="utf-8").read().splitlines()
    i = 0
    while i < len(lines):
        m = re.match(r"^CREATE TABLE `(\w+)` \($", lines[i])
        if not m:
            i += 1
            continue
        name = m.group(1)
        i += 1
        part = dict(cols=[], pk=[], uniques=[], keys=[], fks=[], on_update=[])
        while i < len(lines) and not lines[i].startswith(") ENGINE"):
            raw = lines[i].rstrip()
            if raw.endswith(","):
                raw = raw[:-1]
            body = raw.strip()
            if not body:
                i += 1
                continue
            if body.startswith("PRIMARY KEY"):
                part["pk"] = re.findall(r"`(\w+)`", body)
            elif body.startswith("UNIQUE KEY"):
                um = re.match(r"UNIQUE KEY `(\w+)` \(([^)]+)\)", body)
                part["uniques"].append(
                    (um.group(1), [c.strip(" `") for c in um.group(2).split(",")]))
            elif re.match(r"^(?:\w+ )?KEY `", body):
                km = re.match(r"(?:\w+ )?KEY `(\w+)` \(([^)]+)\)", body)
                part["keys"].append(
                    (km.group(1), [c.strip(" `") for c in km.group(2).split(",")]))
            elif body.startswith("CONSTRAINT"):
                fm = re.match(
                    r"CONSTRAINT `(\w+)` FOREIGN KEY \(([^)]+)\) "
                    r"REFERENCES `(\w+)` \(([^)]+)\)(.*)$", body)
                if not fm:
                    raise SystemExit("BAD FK in %s: %r" % (name, body))
                part["fks"].append((
                    fm.group(1),
                    [c.strip(" `") for c in fm.group(2).split(",")],
                    fm.group(3),
                    [c.strip(" `") for c in fm.group(4).split(",")],
                    fm.group(5).strip(),
                ))
            elif body.startswith("`"):
                col, converted, on_update = convert_column(name, lines[i])
                part["cols"].append(converted)
                if on_update:
                    part["on_update"].append(col)
            else:
                raise SystemExit("UNKNOWN BODY LINE in %s: %r" % (name, body))
            i += 1
        i += 1  # skip ') ENGINE=...'
        tables[name] = part

    if not tables:
        raise SystemExit("no tables parsed - is %s the mysqldump?" % SRC)

    # FK targets must be protected by PK/UNIQUE in Postgres
    for tname, part in tables.items():
        for fk, cols, ref_t, ref_c, _tail in part["fks"]:
            ref = tables.get(ref_t)
            if ref is None:
                raise SystemExit("FK %s references unknown table %s" % (fk, ref_t))
            protected = set(ref["pk"])
            for _n, ucols in ref["uniques"]:
                protected.update(ucols)
            for c in ref_c:
                if c not in protected:
                    raise SystemExit(
                        "FK %s -> %s.%s is not PK/UNIQUE - add a unique index"
                        % (fk, ref_t, c))
    return tables


def render(tables):
    out = []
    out.append("-- PractiCore PostgreSQL schema for Supabase.")
    out.append("--")
    out.append("-- Converted from the authoritative MariaDB dump of the `practicore`")
    out.append("-- database (mysqldump --no-data, every migration 001-014 already applied)")
    out.append("-- with _convert_schema.py. This file is the single source of truth for a")
    out.append("-- fresh Postgres database; the numbered MySQL files under migrations/")
    out.append("-- remain as history for the MySQL repository (PractiCore---mysql).")
    out.append("--")
    out.append("-- Apply: paste into the Supabase SQL Editor, or")
    out.append("--   psql \"$DATABASE_URL\" -f migrations/000_full_schema.sql")
    out.append("--")
    out.append("-- Re-running drops and recreates every table, so only use on a fresh database.")
    out.append("")

    # 1. tables (no FKs - added after every table exists)
    used_constraint_names = set()
    for name, part in tables.items():
        out.append("DROP TABLE IF EXISTS %s CASCADE;" % name)
        out.append("CREATE TABLE %s (" % name)
        body = ["    " + c for c in part["cols"]]
        if part["pk"]:
            body.append("    PRIMARY KEY (%s)" % ", ".join(part["pk"]))
        for uname, ucols in part["uniques"]:
            # A UNIQUE constraint's name doubles as its index name, and index
            # names are global to the schema: students.email and users.email
            # would both want `email`. Collisions get the table name prefixed.
            final = uname
            if final in used_constraint_names:
                final = "%s_%s" % (name, uname)
            used_constraint_names.add(final)
            body.append("    CONSTRAINT %s UNIQUE (%s)" % (final, ", ".join(ucols)))
        out.append(",\n".join(body))
        out.append(");")
        out.append("")

    # 2. secondary indexes (names deduped across the schema)
    seen = set()
    for name, part in tables.items():
        unique_sets = {tuple(ucols) for _n, ucols in part["uniques"]}
        for iname, icols in part["keys"]:
            if tuple(icols) in unique_sets:
                continue  # already covered by the UNIQUE constraint
            final = iname
            n = 1
            while final in seen:
                n += 1
                final = "%s_%d" % (iname, n)
            seen.add(final)
            out.append("CREATE INDEX %s ON %s (%s);"
                       % (final, name, ", ".join(icols)))
    out.append("")

    # 3. foreign keys
    for name, part in tables.items():
        for fk, cols, ref_t, ref_c, tail in part["fks"]:
            out.append(
                "ALTER TABLE %s ADD CONSTRAINT %s FOREIGN KEY (%s) "
                "REFERENCES %s (%s)%s;"
                % (name, fk, ", ".join(cols), ref_t, ", ".join(ref_c),
                   (" " + tail) if tail else ""))
    out.append("")

    # 4. ON UPDATE CURRENT_TIMESTAMP -> triggers
    trigger_cols = OrderedDict()
    for name, part in tables.items():
        for col in part["on_update"]:
            trigger_cols.setdefault(col, []).append(name)
    for col, tnames in trigger_cols.items():
        fn = "set_%s" % col
        out.append("CREATE OR REPLACE FUNCTION %s() RETURNS trigger "
                   "LANGUAGE plpgsql AS $$" % fn)
        out.append("BEGIN NEW.%s := CURRENT_TIMESTAMP; RETURN NEW; END $$;" % col)
        for tname in tnames:
            out.append("CREATE TRIGGER trg_%s_%s BEFORE UPDATE ON %s "
                       "FOR EACH ROW EXECUTE FUNCTION %s();"
                       % (tname, col, tname, fn))
        out.append("")
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    parsed = convert()
    sql = render(parsed)
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(sql)
    print("tables: %d -> %s" % (len(parsed), OUT))
    for t, p in parsed.items():
        note = ("  [ON UPDATE: %s]" % ", ".join(p["on_update"])) if p["on_update"] else ""
        print("  %-34s cols=%-3d fks=%d%s" % (t, len(p["cols"]), len(p["fks"]), note))



